name: file_structure_visualiser
description: A clean file structure creator & visualiser.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  archive:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
